universe = vanilla
# Name the log file:
log = interactive.log

# Name the files where standard output and error should be saved:
output = process.out
error = process.err

# If you wish to compile code, you'll need the below lines. 
#  Otherwise, LEAVE THEM OUT if you just want to interactively test!
+IsBuildJob = true
requirements = (OpSysAndVer =?= "SL6") && ( IsBuildSlot == true )

transfer_input_files = R-3.2.5.tar.gz,install_packages.R,install_r.sh

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue
