# For CHTC
universe = vanilla
log = runs/_logs/map_$(Cluster).log
error = runs/_logs/map_$(Cluster)_$(Process).err
output = runs/_logs/map_$(Cluster)_$(Process).out
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)

# For the job:
executable = map.sh
arguments = $(Process)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
# input: 
transfer_input_files = rqtl_inputs.rdata,map.r,R.tar.gz
# Must match directory name specified in map.r file in field "dir_transfered_by_condor"
transfer_output_files = runs

request_cpus = 1
request_memory = 8GB
request_disk = 500MB

# Queue will get top queue#/#tests traits to map from traits list file
queue 584
